[servers]
	# Configure your servers here. Each key represents the server's name, and the value
	# represents the IP address of the server to connect to.
	lobby = "127.0.0.1:25566"
	
[forced-hosts]
	# Configure your forced hosts here.
	"lobby.example.com" = ["lobby"]
